FROM golang:1.21.0 AS build

COPY ./Database-api /Database-api
COPY ./Crawler /Crawler

WORKDIR /Crawler/cmd
RUN CGO_ENABLED=0 go build -v -o main .


FROM alpine AS api
COPY --from=build /Crawler/cmd/main /

CMD ["/main"]