apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-api
  template:
    metadata:
      labels:
        app: db-api
    spec:
      containers:
        - name: db-api-container
          image: db-api:v1
          imagePullPolicy: Always
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
            - name: Atlas_Info
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: Atlas_Info
          resources:
            limits:
              cpu: 200m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi